"""add_indexes_to_member

Revision ID: 2dd02affd18b
Revises: b2f2c8c4a1e9
Create Date: 2026-04-14 19:17:36.748088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd02affd18b'
down_revision: Union[str, Sequence[str], None] = 'b2f2c8c4a1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_account_approved_birth_month_birth_day'), table_name='members')
    op.drop_index(op.f('ix_members_account_approved_created_at'), table_name='members')
    op.drop_index(op.f('ix_members_account_approved_status'), table_name='members')
    op.create_index(op.f('ix_members_created_at'), 'members', ['created_at'], unique=False)
    op.create_index(op.f('ix_members_first_name'), 'members', ['first_name'], unique=False)
    op.create_index(op.f('ix_members_last_name'), 'members', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_last_name'), table_name='members')
    op.drop_index(op.f('ix_members_first_name'), table_name='members')
    op.drop_index(op.f('ix_members_created_at'), table_name='members')
    op.create_index(op.f('ix_members_account_approved_status'), 'members', ['account_approved', 'status'], unique=False)
    op.create_index(op.f('ix_members_account_approved_created_at'), 'members', ['account_approved', 'created_at'], unique=False)
    op.create_index(op.f('ix_members_account_approved_birth_month_birth_day'), 'members', ['account_approved', 'birth_month', 'birth_day'], unique=False)
    # ### end Alembic commands ###
