"""initial sync and add indexes

Revision ID: f16babe2eb9b
Revises: 
Create Date: 2026-04-11 23:00:52.039561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16babe2eb9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_members_account_approved'), 'members', ['account_approved'], unique=False)
    op.create_index(op.f('ix_members_birth_month'), 'members', ['birth_month'], unique=False)
    op.create_index(op.f('ix_members_status'), 'members', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_status'), table_name='members')
    op.drop_index(op.f('ix_members_birth_month'), table_name='members')
    op.drop_index(op.f('ix_members_account_approved'), table_name='members')
    # ### end Alembic commands ###
